services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_service_db

    environment:
      POSTGRES_DB: payment_service_db
      POSTGRES_USER: PaymentAdmin
      POSTGRES_PASSWORD: "5#0{uz3Ws/£"

    ports:
      - "5251:5432"

    volumes:
      - pgdata_fresh:/var/lib/postgresql/data

volumes:
  pgdata_fresh: