server.port=${SERVER_PORT:7021}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/payment/api}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

bank.visa.url=${BANK_VISA_URL}
bank.mastercard.url=${BANK_MASTERCARD_URL}
bank.nubank.url=${BANK_NUBANK_URL}