server.port=7021
server.servlet.context-path=/payment/api
spring.datasource.url=jdbc:postgresql://localhost:5251/payment_service_db
spring.datasource.username=PaymentAdmin
spring.datasource.password=5#0{uz3Ws/£


spring.jpa.hibernate.ddl-auto=create-drop